import progress from 'eslint-plugin-file-progress';

export default [
    progress.configs['recommended-ci'],
    {
        ignores: [
            '*/icons/all.ts',
            '**/tests-report/**',
            '**/snapshots/**',
            '**/test-results/**',
            '404.html',
            '*.jpg',
            '*.svg',
            '*.less',
            '*.scss',
            '*.txt',
            '*.png',
            '*.jpg',
            '*.webmanifest',
            '*.pdf',
            '*.mp3',
            '*.ogv',
            '*.mp4',
            '*.ico',
            '*.xml',
            '*.md',
            'LICENSE',
            'jest.preset.js',
            '*.config.js',
            'node_modules',
            'dist',
            '**/node_modules/**',
            '**/*@dasherize__/**',
            '**/coverage/**',
            'eslintrc.js',
            '.eslintrc.js',
            '**/*.d.ts',
            '**/dist/**',
            '**/docs/**',
            '**/bin/**',
            '.cache/**',
            '.git/**',
            '.idea/**',
        ],
    },
    {
        rules: {
            semi: 'error',
            'prefer-const': 'error',
        },
    },
];
