module.exports = {
    $schema:
        'https://raw.githubusercontent.com/streetsidesoftware/master/cspell.schema.json',
    caseSensitive: false,
    files: ['*/*.*'],
    ignorePaths: [
        '**/LICENSE',
        '**/.github/CODEOWNERS',
        '**/CHANGELOG.md',
        '**/.cspell.json',
        '**/.git/**',
        '**/dist/**',
        '**/cspell/**',
        '**/assets/**',
        '**/node_modules/**',
        '**/*.{log,svg,snap,png,ogv,yml,less,hbs}',
    ],
    ignoreRegExpList: [
        '\\(https?://.*?\\)',
        '\\/{1}.+\\/{1}',
        '\\%2F.+',
        '\\%2C.+',
        '\\ɵ.+',
        '\\ыва.+',
    ],
    import: [
        './configs/locales/latin.json',
        './configs/locales/dutch.json',
        './configs/locales/arabic.json',
        './configs/locales/ru.json',
        './configs/all.json',
    ],
    language: 'en,ru,ar,lorem',
    useGitignore: true,
};
