module.exports = {
    overrides: [
        {
            files: ['*'],
            rules: {
                '@angular-eslint/component-max-inline-declarations': 'off',
                '@angular-eslint/component-selector': 'off',
                '@angular-eslint/no-forward-ref': 'off',
                '@angular-eslint/no-host-metadata-property': 'off',
                '@angular-eslint/no-input-rename': 'off',
                '@angular-eslint/no-inputs-metadata-property': 'off',
                '@angular-eslint/no-output-rename': 'off',
                '@angular-eslint/no-outputs-metadata-property': 'off',
                '@angular-eslint/no-pipe-impure': 'off',
                '@angular-eslint/sort-ngmodule-metadata-arrays': 'off',
                '@angular-eslint/use-component-selector': 'off',
                '@angular-eslint/use-component-view-encapsulation': 'off',
                '@angular-eslint/use-injectable-provided-in': 'off',
                '@typescript-eslint/ban-ts-comment': 'off',
                '@typescript-eslint/no-empty-function': 'off',
                '@typescript-eslint/no-non-null-assertion': 'off',
                '@typescript-eslint/no-shadow': 'off',
                '@typescript-eslint/no-unnecessary-condition': 'off',
                '@typescript-eslint/no-unsafe-member-access': 'off',
                '@typescript-eslint/no-unsafe-return': 'off',
                '@typescript-eslint/no-useless-constructor': 'off',
                '@typescript-eslint/no-var-requires': 'off',
                '@typescript-eslint/prefer-nullish-coalescing': 'off',
                '@typescript-eslint/prefer-readonly-parameter-types': 'off',
                '@typescript-eslint/strict-boolean-expressions': 'off',
                'default-case-last': 'off',
                'default-param-last': 'off',
                'eslint-comments/disable-enable-pair': 'off',
                'eslint-comments/no-unlimited-disable': 'off',
                'import/no-cycle': 'off',
                'import/no-deprecated': 'off',
                'import/no-dynamic-require': 'off',
                'import/no-relative-packages': 'off',
                'max-nested-callbacks': 'off',
                'max-statements': 'off',
                'no-bitwise': 'off',
                'no-constructor-return': 'off',
                'no-empty-function': 'off',
                'no-loop-func': 'off',
                'no-prototype-builtins': 'off',
                'prettier/prettier': 'off',
                'promise/catch-or-return': 'off',
                'promise/no-nesting': 'off',
                quotes: 'off',
                'rxjs/no-ignored-takewhile-value': 'off',
                'spaced-comment': 'off',
            },
        },
    ],
};
