module.exports = {
    overrides: [
        {
            files: ['*.ts'],
            parser: '@typescript-eslint/parser',
            plugins: ['@typescript-eslint'],
            rules: {
                '@typescript-eslint/lines-between-class-members': [
                    'error',
                    'always',
                    {exceptAfterOverload: true, exceptAfterSingleLine: true},
                ],
                '@typescript-eslint/padding-line-between-statements': [
                    'error',
                    {blankLine: 'always', next: 'block', prev: '*'},
                    {blankLine: 'always', next: '*', prev: 'block'},
                    {blankLine: 'always', next: 'block-like', prev: '*'},
                    {blankLine: 'always', next: '*', prev: 'block-like'},
                    {blankLine: 'always', next: 'return', prev: '*'},
                    {blankLine: 'always', next: '*', prev: 'directive'},
                    {blankLine: 'always', next: ['interface', 'type'], prev: '*'},
                    {blankLine: 'always', next: '*', prev: ['const', 'let', 'var']},
                    {blankLine: 'always', next: 'class', prev: '*'},
                    {blankLine: 'always', next: '*', prev: 'class'},
                    {
                        blankLine: 'any',
                        next: ['const', 'let', 'var', 'export'],
                        prev: ['const', 'let', 'var', 'export'],
                    },
                    {blankLine: 'any', next: ['case', 'default'], prev: '*'},
                    {blankLine: 'any', next: '*', prev: ['case', 'default']},
                    {blankLine: 'any', next: 'directive', prev: 'directive'},
                ],
                'lines-around-comment': [
                    'error',
                    {
                        afterBlockComment: false,
                        afterLineComment: false,
                        allowArrayEnd: true,
                        allowArrayStart: true,
                        allowBlockEnd: true,
                        allowBlockStart: true,
                        allowClassEnd: true,
                        allowClassStart: true,
                        allowObjectEnd: true,
                        allowObjectStart: true,
                        applyDefaultIgnorePatterns: true,
                        beforeBlockComment: false,
                        beforeLineComment: false,
                    },
                ],
                'lines-between-class-members': 'off',
                'padding-line-between-statements': 'off',
            },
        },
    ],
};
