/**
 * @type {import('eslint').Linter.Config}
 */
module.exports = {
    configs: {
        all: require('./all.js'),
        base: require('./configs/base/index.js'),
        cypress: require('./configs/cypress.js'),
        'decorator-position': require('./configs/angular/decorator-position/index.js'),
        experimental: require('./configs/angular/experimental/index.js'),
        'file-progress': require('./configs/angular/file-progress/index.js'),
        'function-return-type': require('./configs/angular/function-return-type/index.js'),
        functional: require('./configs/functional.js'),
        html: require('./configs/angular/html/index.js'),
        'html-eslint': require('./configs/angular/html-eslint/index.js'),
        imports: require('./configs/angular/imports/index.js'),
        jest: require('./configs/jest.js'),
        'line-statements': require('./configs/angular/line-statements/index.js'),
        'member-ordering': require('./configs/angular/member-ordering/index.js'),
        'naming-convention': require('./configs/naming-convention.js'),
        ng: require('./configs/ng.js'),
        'no-restricted-syntax': require('./configs/no-restricted-syntax.js'),
        off: require('./configs/off.js'),
        playwright: require('./configs/playwright.js'),
        promise: require('./configs/angular/promise/index.js'),
        recommended: require('./configs/angular/recommended/index.js'),
        rxjs: require('./configs/angular/rxjs/index.js'),
        sonar: require('./configs/sonar.js'),
        taiga: require('./configs/taiga.js'),
        'taiga-naming-convention': require('./configs/taiga-naming-convention.js'),
        typescript: require('./configs/typescript.js'),
        unicorn: require('./configs/angular/unicorn/index.js'),
    },
    rules: {
        'decorator-key-sort': require('./rules/decorator-key-sort'),
        'injection-token-description': require('./rules/injection-token-description'),
        'no-assert-without-ng-dev-mode': require('./rules/no-assert-without-ng-dev-mode'),
        'no-deep-imports': require('./rules/no-deep-imports'),
        'no-private-esnext-fields': require('./rules/no-private-esnext-fields'),
        'no-simple-for-of': require('./rules/no-simple-for-of'),
        'no-typeof': require('./rules/no-typeof'),
        'prefer-inject-decorator': require('./rules/prefer-inject-decorator'),
        'prefer-self-destroy-service': require('./rules/prefer-self-destroy-service'),
        'strict-tui-doc-example': require('./rules/strict-tui-doc-example'),
    },
};
